use super::report::CtxcrlStatus;

pub struct CtxcrlRule {
    pub pattern: &'static str,
    pub ctxcrl_cmd: &'static str,
    pub rewrite_prefixes: &'static [&'static str],
    pub category: &'static str,
    pub savings_pct: f64,
    pub subcmd_savings: &'static [(&'static str, f64)],
    pub subcmd_status: &'static [(&'static str, CtxcrlStatus)],
}

pub const RULES: &[CtxcrlRule] = &[
    CtxcrlRule {
        pattern: r"^(?:git|yadm)\s+(?:-[Cc]\s+\S+\s+)*(status|log|diff|show|add|commit|push|pull|branch|fetch|stash|worktree|checkout|switch|restore|merge|rebase|reset|tag|remote|cherry-pick)(?:\s|$)",
        ctxcrl_cmd: "contextcrawler git",
        rewrite_prefixes: &["git", "yadm"],
        category: "Git",
        savings_pct: 70.0,
        subcmd_savings: &[
            ("diff", 80.0),
            ("show", 80.0),
            ("add", 59.0),
            ("commit", 59.0),
            ("checkout", 30.0),
            ("switch", 30.0),
            ("restore", 30.0),
            ("merge", 30.0),
            ("rebase", 30.0),
            ("reset", 30.0),
            ("tag", 30.0),
            ("remote", 30.0),
            ("cherry-pick", 30.0),
        ],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^gh\s+(pr|issue|run|repo|api|release)",
        ctxcrl_cmd: "contextcrawler gh",
        rewrite_prefixes: &["gh"],
        category: "GitHub",
        savings_pct: 82.0,
        subcmd_savings: &[("pr", 87.0), ("run", 82.0), ("issue", 80.0)],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^glab\s+(mr|issue|ci|pipeline|api|release)",
        ctxcrl_cmd: "contextcrawler glab",
        rewrite_prefixes: &["glab"],
        category: "GitLab",
        savings_pct: 82.0,
        subcmd_savings: &[("mr", 87.0), ("ci", 82.0), ("issue", 80.0)],
        subcmd_status: &[],
    },
    CtxcrlRule {
        // `(?:\+\S+\s+)?` tolerates a rustup `+toolchain` selector
        // (`cargo +nightly test`). `normalise_command` strips it before the
        // classifier runs, but accepting it inline keeps classification robust
        // regardless of normalisation order. Subcommand stays in capture 1.
        pattern: r"^cargo\s+(?:\+\S+\s+)?(build|test|clippy|check|fmt|install)",
        ctxcrl_cmd: "contextcrawler cargo",
        rewrite_prefixes: &["cargo"],
        category: "Cargo",
        savings_pct: 80.0,
        subcmd_savings: &[("test", 90.0), ("check", 80.0)],
        subcmd_status: &[("fmt", CtxcrlStatus::Passthrough)],
    },
    CtxcrlRule {
        pattern: r"^pnpm\s+(exec|i|install|list|ls|outdated|run|run-script)",
        ctxcrl_cmd: "contextcrawler pnpm",
        rewrite_prefixes: &["pnpm"],
        category: "PackageManager",
        savings_pct: 80.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^npm\s+(exec|run|run-script|rum|urn|x)(\s|$)",
        ctxcrl_cmd: "contextcrawler npm",
        rewrite_prefixes: &["npm"],
        category: "PackageManager",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^npx\s+",
        ctxcrl_cmd: "contextcrawler npx",
        rewrite_prefixes: &["npx"],
        category: "PackageManager",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^(cat|head|tail)\s+",
        ctxcrl_cmd: "contextcrawler read",
        rewrite_prefixes: &["cat", "head", "tail"],
        category: "Files",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^rg\s+",
        ctxcrl_cmd: "contextcrawler rg",
        rewrite_prefixes: &["rg"],
        category: "Files",
        savings_pct: 75.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^grep\s+",
        ctxcrl_cmd: "contextcrawler grep",
        rewrite_prefixes: &["grep"],
        category: "Files",
        savings_pct: 75.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^ls(\s|$)",
        ctxcrl_cmd: "contextcrawler ls",
        rewrite_prefixes: &["ls"],
        category: "Files",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^find\s+",
        ctxcrl_cmd: "contextcrawler find",
        rewrite_prefixes: &["find"],
        category: "Files",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?tsc(\s|$)",
        ctxcrl_cmd: "contextcrawler tsc",
        rewrite_prefixes: &[
            "npm exec tsc",
            "npm rum tsc",
            "npm run tsc",
            "npm run-script tsc",
            "npm tsc",
            "npm urn tsc",
            "npm x tsc",
            "npx tsc",
            "pnpm dlx tsc",
            "pnpm exec tsc",
            "pnpm run tsc",
            "pnpm run-script tsc",
            "pnpm tsc",
            "pnpx tsc",
            "tsc",
        ],
        category: "Build",
        savings_pct: 83.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?(biome|eslint|lint)(\s|$)",
        ctxcrl_cmd: "contextcrawler lint",
        rewrite_prefixes: &[
            "biome",
            "eslint",
            "lint",
            "npm biome",
            "npm eslint",
            "npm exec biome",
            "npm exec eslint",
            "npm lint",
            "npm rum biome",
            "npm rum eslint",
            "npm rum lint",
            "npm run biome",
            "npm run eslint",
            "npm run lint",
            "npm run-script biome",
            "npm run-script eslint",
            "npm run-script lint",
            "npm urn biome",
            "npm urn eslint",
            "npm urn lint",
            "npm x biome",
            "npm x eslint",
            "npx biome",
            "npx eslint",
            "npx lint",
            "pnpm biome",
            "pnpm dlx biome",
            "pnpm dlx eslint",
            "pnpm eslint",
            "pnpm exec biome",
            "pnpm exec eslint",
            "pnpm lint",
            "pnpm run biome",
            "pnpm run eslint",
            "pnpm run lint",
            "pnpm run-script biome",
            "pnpm run-script eslint",
            "pnpm run-script lint",
            "pnpx biome",
            "pnpx eslint",
            "pnpx lint",
        ],
        category: "Build",
        savings_pct: 84.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?prettier",
        ctxcrl_cmd: "contextcrawler prettier",
        rewrite_prefixes: &[
            "npm exec prettier",
            "npm prettier",
            "npm rum prettier",
            "npm run prettier",
            "npm run-script prettier",
            "npm urn prettier",
            "npm x prettier",
            "npx prettier",
            "pnpm dlx prettier",
            "pnpm exec prettier",
            "pnpm prettier",
            "pnpm run prettier",
            "pnpm run-script prettier",
            "pnpx prettier",
            "prettier",
        ],
        category: "Build",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?next\s+build",
        ctxcrl_cmd: "contextcrawler next",
        rewrite_prefixes: &[
            "next build",
            "npm exec next build",
            "npm next build",
            "npm rum next build",
            "npm run next build",
            "npm run-script next build",
            "npm urn next build",
            "npm x next build",
            "npx next build",
            "pnpm dlx next build",
            "pnpm exec next build",
            "pnpm next build",
            "pnpm run next build",
            "pnpm run-script next build",
            "pnpx next build",
        ],
        category: "Build",
        savings_pct: 87.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?jest(\s+run)?(\s|$)",
        ctxcrl_cmd: "contextcrawler jest",
        rewrite_prefixes: &[
            "jest run",
            "jest",
            "npm exec jest run",
            "npm exec jest",
            "npm jest run",
            "npm jest",
            "npm rum jest run",
            "npm rum jest",
            "npm run jest run",
            "npm run jest",
            "npm run-script jest run",
            "npm run-script jest",
            "npm urn jest run",
            "npm urn jest",
            "npm x jest run",
            "npm x jest",
            "npx jest run",
            "npx jest",
            "pnpm dlx jest run",
            "pnpm dlx jest",
            "pnpm exec jest run",
            "pnpm exec jest",
            "pnpm jest run",
            "pnpm jest",
            "pnpm run jest run",
            "pnpm run jest",
            "pnpm run-script jest run",
            "pnpm run-script jest",
            "pnpx jest run",
            "pnpx jest",
        ],
        category: "Tests",
        savings_pct: 99.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?vitest(\s+run)?(\s|$)",
        ctxcrl_cmd: "contextcrawler vitest",
        rewrite_prefixes: &[
            "npm exec vitest run",
            "npm exec vitest",
            "npm rum vitest run",
            "npm rum vitest",
            "npm run vitest run",
            "npm run vitest",
            "npm run-script vitest run",
            "npm run-script vitest",
            "npm urn vitest run",
            "npm urn vitest",
            "npm vitest run",
            "npm vitest",
            "npm x vitest run",
            "npm x vitest",
            "npx vitest run",
            "npx vitest",
            "pnpm dlx vitest run",
            "pnpm dlx vitest",
            "pnpm exec vitest run",
            "pnpm exec vitest",
            "pnpm run vitest run",
            "pnpm run vitest",
            "pnpm run-script vitest run",
            "pnpm run-script vitest",
            "pnpm vitest run",
            "pnpm vitest",
            "pnpx vitest run",
            "pnpx vitest",
            "vitest run",
            "vitest",
        ],
        category: "Tests",
        savings_pct: 99.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?playwright",
        ctxcrl_cmd: "contextcrawler playwright",
        rewrite_prefixes: &[
            "npm exec playwright",
            "npm playwright",
            "npm rum playwright",
            "npm run playwright",
            "npm run-script playwright",
            "npm urn playwright",
            "npm x playwright",
            "npx playwright",
            "playwright",
            "pnpm dlx playwright",
            "pnpm exec playwright",
            "pnpm playwright",
            "pnpm run playwright",
            "pnpm run-script playwright",
            "pnpx playwright",
        ],
        category: "Tests",
        savings_pct: 94.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?prisma",
        ctxcrl_cmd: "contextcrawler prisma",
        rewrite_prefixes: &[
            "npm exec prisma",
            "npm prisma",
            "npm rum prisma",
            "npm run prisma",
            "npm run-script prisma",
            "npm urn prisma",
            "npm x prisma",
            "npx prisma",
            "pnpm dlx prisma",
            "pnpm exec prisma",
            "pnpm prisma",
            "pnpm run prisma",
            "pnpm run-script prisma",
            "pnpx prisma",
            "prisma",
        ],
        category: "Build",
        savings_pct: 88.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^docker\s+(ps|images|logs|run|exec|build|compose\s+(ps|logs|build))",
        ctxcrl_cmd: "contextcrawler docker",
        rewrite_prefixes: &["docker"],
        category: "Infra",
        savings_pct: 85.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^kubectl\s+(get|logs|describe|apply)",
        ctxcrl_cmd: "contextcrawler kubectl",
        rewrite_prefixes: &["kubectl"],
        category: "Infra",
        savings_pct: 85.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^tree(\s|$)",
        ctxcrl_cmd: "contextcrawler tree",
        rewrite_prefixes: &["tree"],
        category: "Files",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^diff\s+",
        ctxcrl_cmd: "contextcrawler diff",
        rewrite_prefixes: &["diff"],
        category: "Files",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^curl\s+",
        ctxcrl_cmd: "contextcrawler curl",
        rewrite_prefixes: &["curl"],
        category: "Network",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^wget\s+",
        ctxcrl_cmd: "contextcrawler wget",
        rewrite_prefixes: &["wget"],
        category: "Network",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^(python3?\s+-m\s+)?mypy(\s|$)",
        ctxcrl_cmd: "contextcrawler mypy",
        rewrite_prefixes: &["python3 -m mypy", "python -m mypy", "mypy"],
        category: "Build",
        savings_pct: 80.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^ruff\s+(check|format)",
        ctxcrl_cmd: "contextcrawler ruff",
        rewrite_prefixes: &["ruff"],
        category: "Python",
        savings_pct: 80.0,
        subcmd_savings: &[("check", 80.0), ("format", 75.0)],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^(python[0-9.]*\s+-m\s+)?pytest(\s|$)",
        ctxcrl_cmd: "contextcrawler pytest",
        rewrite_prefixes: &["python3 -m pytest", "python -m pytest", "pytest"],
        category: "Python",
        savings_pct: 90.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^(pip3?|uv\s+pip)\s+(list|outdated|install|show)",
        ctxcrl_cmd: "contextcrawler pip",
        rewrite_prefixes: &["pip3", "pip", "uv pip"],
        category: "Python",
        savings_pct: 75.0,
        subcmd_savings: &[("list", 75.0), ("outdated", 80.0)],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^go\s+(test|build|vet)",
        ctxcrl_cmd: "contextcrawler go",
        rewrite_prefixes: &["go"],
        category: "Go",
        savings_pct: 85.0,
        subcmd_savings: &[("test", 90.0), ("build", 80.0), ("vet", 75.0)],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^(?:golangci-lint|golangci)\s+(run)(?:\s|$)",
        ctxcrl_cmd: "contextcrawler golangci-lint run",
        rewrite_prefixes: &["golangci-lint run", "golangci run"],
        category: "Go",
        savings_pct: 85.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^bundle\s+(install|update)\b",
        ctxcrl_cmd: "contextcrawler bundle",
        rewrite_prefixes: &["bundle"],
        category: "Ruby",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^(?:bundle\s+exec\s+)?(?:bin/)?(?:rake|rails)\s+test",
        ctxcrl_cmd: "contextcrawler rake",
        rewrite_prefixes: &[
            "bundle exec rails",
            "bundle exec rake",
            "bin/rails",
            "rails",
            "rake",
        ],
        category: "Ruby",
        savings_pct: 85.0,
        subcmd_savings: &[("test", 90.0)],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^(?:bundle\s+exec\s+)?rspec(?:\s|$)",
        ctxcrl_cmd: "contextcrawler rspec",
        rewrite_prefixes: &["bundle exec rspec", "bin/rspec", "rspec"],
        category: "Tests",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^(?:bundle\s+exec\s+)?rubocop(?:\s|$)",
        ctxcrl_cmd: "contextcrawler rubocop",
        rewrite_prefixes: &["bundle exec rubocop", "rubocop"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^aws\s+",
        ctxcrl_cmd: "contextcrawler aws",
        rewrite_prefixes: &["aws"],
        category: "Infra",
        savings_pct: 80.0,
        subcmd_savings: &[
            ("sts", 80.0),
            ("s3", 60.0),
            ("ec2", 85.0),
            ("ecs", 90.0),
            ("rds", 80.0),
            ("cloudformation", 90.0),
            ("logs", 88.0),
            ("lambda", 90.0),
            ("iam", 85.0),
            ("dynamodb", 70.0),
            ("s3api", 75.0),
            ("eks", 87.0),
            ("sqs", 78.0),
            ("secretsmanager", 75.0),
        ],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^psql(\s|$)",
        ctxcrl_cmd: "contextcrawler psql",
        rewrite_prefixes: &["psql"],
        category: "Infra",
        savings_pct: 75.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^ansible-playbook\b",
        ctxcrl_cmd: "contextcrawler ansible-playbook",
        rewrite_prefixes: &["ansible-playbook"],
        category: "Infra",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^brew\s+(install|upgrade)\b",
        ctxcrl_cmd: "contextcrawler brew",
        rewrite_prefixes: &["brew"],
        category: "PackageManager",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^composer\s+(install|update|require)\b",
        ctxcrl_cmd: "contextcrawler composer",
        rewrite_prefixes: &["composer"],
        category: "PackageManager",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^df(\s|$)",
        ctxcrl_cmd: "contextcrawler df",
        rewrite_prefixes: &["df"],
        category: "System",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^dotnet\s+build\b",
        ctxcrl_cmd: "contextcrawler dotnet",
        rewrite_prefixes: &["dotnet"],
        category: "Build",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^du\b",
        ctxcrl_cmd: "contextcrawler du",
        rewrite_prefixes: &["du"],
        category: "System",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^fail2ban-client\b",
        ctxcrl_cmd: "contextcrawler fail2ban-client",
        rewrite_prefixes: &["fail2ban-client"],
        category: "Infra",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^gcloud\b",
        ctxcrl_cmd: "contextcrawler gcloud",
        rewrite_prefixes: &["gcloud"],
        category: "Infra",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^(?:\./gradlew|gradlew\.bat|gradlew|gradle)(?:\s+(test|build|clean|assemble\w*|install\w*|check|lint\w*|dependencies))?(\s|$)",
        ctxcrl_cmd: "contextcrawler gradlew",
        rewrite_prefixes: &["./gradlew", "gradlew.bat", "gradlew", "gradle"],
        category: "Build",
        savings_pct: 75.0,
        subcmd_savings: &[("test", 90.0), ("build", 80.0), ("check", 80.0)],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^hadolint\b",
        ctxcrl_cmd: "contextcrawler hadolint",
        rewrite_prefixes: &["hadolint"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^helm\b",
        ctxcrl_cmd: "contextcrawler helm",
        rewrite_prefixes: &["helm"],
        category: "Infra",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^iptables\b",
        ctxcrl_cmd: "contextcrawler iptables",
        rewrite_prefixes: &["iptables"],
        category: "Infra",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^make\b",
        ctxcrl_cmd: "contextcrawler make",
        rewrite_prefixes: &["make"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^markdownlint\b",
        ctxcrl_cmd: "contextcrawler markdownlint",
        rewrite_prefixes: &["markdownlint"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^mix\s+(compile|format)(\s|$)",
        ctxcrl_cmd: "contextcrawler mix",
        rewrite_prefixes: &["mix"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^mvn\s+(compile|package|clean|install)\b",
        ctxcrl_cmd: "contextcrawler mvn",
        rewrite_prefixes: &["mvn"],
        category: "Build",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^ping\b",
        ctxcrl_cmd: "contextcrawler ping",
        rewrite_prefixes: &["ping"],
        category: "Network",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^pio\s+run",
        ctxcrl_cmd: "contextcrawler pio",
        rewrite_prefixes: &["pio"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^poetry\s+(install|lock|update)\b",
        ctxcrl_cmd: "contextcrawler poetry",
        rewrite_prefixes: &["poetry"],
        category: "Python",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^pre-commit\b",
        ctxcrl_cmd: "contextcrawler pre-commit",
        rewrite_prefixes: &["pre-commit"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^ps(\s|$)",
        ctxcrl_cmd: "contextcrawler ps",
        rewrite_prefixes: &["ps"],
        category: "System",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^quarto\s+render",
        ctxcrl_cmd: "contextcrawler quarto",
        rewrite_prefixes: &["quarto"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^rsync\b",
        ctxcrl_cmd: "contextcrawler rsync",
        rewrite_prefixes: &["rsync"],
        category: "Network",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^shellcheck\b",
        ctxcrl_cmd: "contextcrawler shellcheck",
        rewrite_prefixes: &["shellcheck"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^shopify\s+theme\s+(push|pull)",
        ctxcrl_cmd: "contextcrawler shopify",
        rewrite_prefixes: &["shopify"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^sops\b",
        ctxcrl_cmd: "contextcrawler sops",
        rewrite_prefixes: &["sops"],
        category: "Infra",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^swift\s+(build|test)\b",
        ctxcrl_cmd: "contextcrawler swift",
        rewrite_prefixes: &["swift"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[("test", 90.0)],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^systemctl\s+status\b",
        ctxcrl_cmd: "contextcrawler systemctl",
        rewrite_prefixes: &["systemctl"],
        category: "System",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^terraform\s+plan",
        ctxcrl_cmd: "contextcrawler terraform",
        rewrite_prefixes: &["terraform"],
        category: "Infra",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^tofu\s+(fmt|init|plan|validate)(\s|$)",
        ctxcrl_cmd: "contextcrawler tofu",
        rewrite_prefixes: &["tofu"],
        category: "Infra",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^trunk\s+build",
        ctxcrl_cmd: "contextcrawler trunk",
        rewrite_prefixes: &["trunk"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^uv\s+(sync|pip\s+install)\b",
        ctxcrl_cmd: "contextcrawler uv",
        rewrite_prefixes: &["uv"],
        category: "Python",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^yamllint\b",
        ctxcrl_cmd: "contextcrawler yamllint",
        rewrite_prefixes: &["yamllint"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^wc(\s|$)",
        ctxcrl_cmd: "contextcrawler wc",
        rewrite_prefixes: &["wc"],
        category: "Files",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^gt\s+",
        ctxcrl_cmd: "contextcrawler gt",
        rewrite_prefixes: &["gt"],
        category: "Git",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    CtxcrlRule {
        pattern: r"^liquibase(?:\s|$)",
        ctxcrl_cmd: "contextcrawler liquibase",
        rewrite_prefixes: &["liquibase"],
        category: "Infra",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
];

pub const IGNORED_PREFIXES: &[&str] = &[
    "cd ",
    "cd\t",
    "echo ",
    "printf ",
    "export ",
    "source ",
    "mkdir ",
    "rm ",
    "mv ",
    "cp ",
    "chmod ",
    "chown ",
    "touch ",
    "which ",
    "type ",
    "test ",
    "true",
    "false",
    "sleep ",
    "wait",
    "kill ",
    "set ",
    "unset ",
    "sort ",
    "uniq ",
    "tr ",
    "cut ",
    "awk ",
    "sed ",
    "python3 -c",
    "python -c",
    "node -e",
    "ruby -e",
    "rtk ",
    // Post-#62: current rewrite output uses this prefix; classify it as
    // already-wrapped so the rewriter doesn't double-wrap.
    "contextcrawler ",
    // #86: tirith is our own defense-in-depth gate, not an unsupported command.
    "tirith ",
    "pwd",
    "bash ",
    "sh ",
    "then\n",
    "then ",
    "else\n",
    "else ",
    "do\n",
    "do ",
    "for ",
    "while ",
    "if ",
    "case ",
];

pub const IGNORED_EXACT: &[&str] = &[
    "cd", "echo", "true", "false", "wait", "pwd", "bash", "sh", "fi", "done",
];
